export * from "./header";
export * from "./person-menu";
export * from "./menu-nav";
export * from "./menu-burger"
export * from './main';
export * from './hero';
export * from "./hero-top";
export * from './hero-img';
export * from "./hero-info";
export * from "./content";
export * from "./feedbacks";
export * from "./hero-bot";
export * from "./values";
export * from "./footer";
export * from "./Pages/Home/Home.jsx";
export * from "./Pages/Games/Games.jsx";
export * from "./Pages/Features/Features.jsx";
export * from "../assets/scripts/mock";
export * from  "../assets/scripts/localStorage";
