export * from "./hero";
export * from './hero-top';
export * from "./hero-img";
export * from "./hero-info";
export * from "./hero-bot";
export * from './main';
export * from './values';
export * from "./feedbacks"
export * from "./content";